[package]
name = "mih-rs"
version = "0.1.0"
authors = ["Shunsuke Kanda (kampersanda) <shnsk.knd@gmail.com>"]
description = "Multi-index hashing (MIH) for neighbor searches on 64-bit codes in the Hamming space."
license = "MIT"
repository = "https://github.com/kampersanda/mih-rs"
homepage = "https://github.com/kampersanda/mih-rs"
keywords = ["nns"]
categories = ["data-structures"]
edition = "2018"

[dependencies]
rand = "0.6"
